import { Injectable, NotFoundException } from '@nestjs/common';
import { EntityType, PaymentStatus, UserRole, WalletOwnerType, WalletTransactionType } from '@prisma/client';
import { PrismaService } from '../../prisma.service';
import { AuditService } from '../audit/audit.service';

@Injectable()
export class WalletsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly auditService: AuditService,
  ) {}

  private toNumber(value: unknown) {
    if (value === null || value === undefined) return 0;
    const parsed = Number(value);
    return Number.isNaN(parsed) ? 0 : parsed;
  }

  private async ensureInstructorWallet(instructorProfileId: string, actorUserId?: string) {
    const wallet = await this.prisma.wallet.upsert({
      where: { instructorProfileId },
      create: {
        ownerType: WalletOwnerType.INSTRUCTOR,
        instructorProfileId,
        currency: 'BRL',
      },
      update: {},
    });

    await this.auditService.log({
      actorUserId,
      entityType: EntityType.WALLET,
      entityId: wallet.id,
      action: 'WALLET_UPSERTED',
      metadataJson: { ownerType: WalletOwnerType.INSTRUCTOR, instructorProfileId },
    });

    return wallet;
  }

  private async ensureSchoolWallet(schoolId: string, actorUserId?: string) {
    const wallet = await this.prisma.wallet.upsert({
      where: { schoolId },
      create: {
        ownerType: WalletOwnerType.SCHOOL,
        schoolId,
        currency: 'BRL',
      },
      update: {},
    });

    await this.auditService.log({
      actorUserId,
      entityType: EntityType.WALLET,
      entityId: wallet.id,
      action: 'WALLET_UPSERTED',
      metadataJson: { ownerType: WalletOwnerType.SCHOOL, schoolId },
    });

    return wallet;
  }

  private async createTransaction(input: {
    walletId: string;
    type: WalletTransactionType;
    amount: number;
    referenceType: EntityType;
    referenceId: string;
    description?: string;
    actorUserId?: string;
  }) {
    const tx = await this.prisma.walletTransaction.create({
      data: {
        walletId: input.walletId,
        type: input.type,
        amount: input.amount,
        referenceType: input.referenceType,
        referenceId: input.referenceId,
        description: input.description,
      },
    });

    await this.auditService.log({
      actorUserId: input.actorUserId,
      entityType: EntityType.WALLET_TRANSACTION,
      entityId: tx.id,
      action: 'WALLET_TRANSACTION_CREATED',
      metadataJson: {
        walletId: input.walletId,
        type: input.type,
        amount: input.amount,
        referenceType: input.referenceType,
        referenceId: input.referenceId,
      },
    });

    return tx;
  }

  private async applyBalances(walletId: string, delta: { available?: number; pending?: number; onHold?: number }) {
    const wallet = await this.prisma.wallet.findUnique({ where: { id: walletId } });
    if (!wallet) throw new NotFoundException('Wallet not found.');

    return this.prisma.wallet.update({
      where: { id: walletId },
      data: {
        balanceAvailable: this.toNumber(wallet.balanceAvailable) + (delta.available ?? 0),
        balancePending: this.toNumber(wallet.balancePending) + (delta.pending ?? 0),
        balanceOnHold: this.toNumber(wallet.balanceOnHold) + (delta.onHold ?? 0),
      },
    });
  }

  private async getWalletByPayment(paymentId: string, actorUserId?: string) {
    const payment = await this.prisma.payment.findUnique({ where: { id: paymentId } });
    if (!payment) {
      throw new NotFoundException('Payment not found.');
    }

    if (payment.instructorProfileId) {
      const wallet = await this.ensureInstructorWallet(payment.instructorProfileId, actorUserId);
      return { wallet, payment };
    }

    if (payment.schoolId) {
      const wallet = await this.ensureSchoolWallet(payment.schoolId, actorUserId);
      return { wallet, payment };
    }

    throw new NotFoundException('No wallet owner found for payment.');
  }

  async registerPendingFromPayment(paymentId: string, actorUserId?: string) {
    const { wallet, payment } = await this.getWalletByPayment(paymentId, actorUserId);

    const exists = await this.prisma.walletTransaction.findFirst({
      where: {
        walletId: wallet.id,
        type: WalletTransactionType.CREDIT,
        referenceType: EntityType.PAYMENT,
        referenceId: payment.id,
      },
    });
    if (exists) {
      return wallet;
    }

    const amountNet = this.toNumber(payment.amount) - this.toNumber(payment.platformFee);

    await this.createTransaction({
      walletId: wallet.id,
      type: WalletTransactionType.CREDIT,
      amount: amountNet,
      referenceType: EntityType.PAYMENT,
      referenceId: payment.id,
      description: 'Pending credit generated by payment capture.',
      actorUserId,
    });

    await this.applyBalances(wallet.id, { pending: amountNet });

    return wallet;
  }

  async movePendingToAvailable(paymentId: string, actorUserId?: string) {
    const { wallet, payment } = await this.getWalletByPayment(paymentId, actorUserId);

    const releaseExists = await this.prisma.walletTransaction.findFirst({
      where: {
        walletId: wallet.id,
        type: WalletTransactionType.RELEASE,
        referenceType: EntityType.PAYMENT,
        referenceId: payment.id,
      },
    });
    if (releaseExists) {
      return wallet;
    }

    const amountNet = this.toNumber(payment.amount) - this.toNumber(payment.platformFee);

    await this.createTransaction({
      walletId: wallet.id,
      type: WalletTransactionType.RELEASE,
      amount: amountNet,
      referenceType: EntityType.PAYMENT,
      referenceId: payment.id,
      description: 'Funds released to available balance.',
      actorUserId,
    });

    await this.applyBalances(wallet.id, { pending: -amountNet, available: amountNet });

    return wallet;
  }

  async holdByPayment(paymentId: string, reason = 'Dispute or safety hold', actorUserId?: string) {
    const { wallet, payment } = await this.getWalletByPayment(paymentId, actorUserId);
    const amountNet = this.toNumber(payment.amount) - this.toNumber(payment.platformFee);

    await this.createTransaction({
      walletId: wallet.id,
      type: WalletTransactionType.HOLD,
      amount: amountNet,
      referenceType: EntityType.PAYMENT,
      referenceId: payment.id,
      description: reason,
      actorUserId,
    });

    const available = this.toNumber(wallet.balanceAvailable);
    const pending = this.toNumber(wallet.balancePending);

    if (available >= amountNet) {
      await this.applyBalances(wallet.id, { available: -amountNet, onHold: amountNet });
    } else if (pending >= amountNet) {
      await this.applyBalances(wallet.id, { pending: -amountNet, onHold: amountNet });
    } else {
      const fromAvailable = Math.max(0, available);
      const remaining = amountNet - fromAvailable;
      await this.applyBalances(wallet.id, { available: -fromAvailable, pending: -remaining, onHold: amountNet });
    }

    return wallet;
  }

  async refundByPayment(paymentId: string, actorUserId?: string) {
    const { wallet, payment } = await this.getWalletByPayment(paymentId, actorUserId);
    const amountNet = this.toNumber(payment.amount) - this.toNumber(payment.platformFee);

    await this.createTransaction({
      walletId: wallet.id,
      type: WalletTransactionType.REFUND,
      amount: amountNet,
      referenceType: EntityType.PAYMENT,
      referenceId: payment.id,
      description: 'Refund applied.',
      actorUserId,
    });

    const available = this.toNumber(wallet.balanceAvailable);
    const onHold = this.toNumber(wallet.balanceOnHold);

    if (available >= amountNet) {
      await this.applyBalances(wallet.id, { available: -amountNet });
    } else if (onHold >= amountNet) {
      await this.applyBalances(wallet.id, { onHold: -amountNet });
    } else {
      const fromAvailable = Math.max(0, available);
      const remaining = amountNet - fromAvailable;
      await this.applyBalances(wallet.id, { available: -fromAvailable, onHold: -remaining });
    }

    return wallet;
  }

  async onPaymentStatusChanged(paymentId: string, status: PaymentStatus, actorUserId?: string) {
    if (status === PaymentStatus.CAPTURED || status === PaymentStatus.PAID) {
      return this.registerPendingFromPayment(paymentId, actorUserId);
    }

    if (status === PaymentStatus.REFUNDED || status === PaymentStatus.CANCELLED) {
      return this.refundByPayment(paymentId, actorUserId);
    }

    return null;
  }

  async getMyWallet(userId: string, role: UserRole) {
    if (role === UserRole.INSTRUCTOR) {
      const instructor = await this.prisma.instructorProfile.findUnique({ where: { userId } });
      if (!instructor) throw new NotFoundException('Instructor profile not found.');
      return this.ensureInstructorWallet(instructor.id, userId);
    }

    if (role === UserRole.SCHOOL_MANAGER) {
      const school = await this.prisma.school.findUnique({ where: { managerUserId: userId } });
      if (!school) throw new NotFoundException('School not found.');
      return this.ensureSchoolWallet(school.id, userId);
    }

    const wallet = await this.prisma.wallet.upsert({
      where: { ownerType_ownerUserId: { ownerType: WalletOwnerType.USER, ownerUserId: userId } },
      create: {
        ownerType: WalletOwnerType.USER,
        ownerUserId: userId,
      },
      update: {},
    });

    await this.auditService.log({
      actorUserId: userId,
      entityType: EntityType.WALLET,
      entityId: wallet.id,
      action: 'WALLET_UPSERTED',
      metadataJson: { ownerType: WalletOwnerType.USER },
    });

    return wallet;
  }

  async getMyTransactions(userId: string, role: UserRole) {
    const wallet = await this.getMyWallet(userId, role);
    return this.prisma.walletTransaction.findMany({
      where: { walletId: wallet.id },
      orderBy: { createdAt: 'desc' },
      take: 300,
    });
  }
}
